config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "about", to: "about#index"
  # get "/", to: "main#index"
  root to: "main#index"

  get "sign_up", to:"registration#new"

  post "sign_up", to: "registration#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to:"sessions#new"

  post "sign_in", to: "sessions#create"

  get "read_articles", to:"articles#index"

  get "password", to: "passwords#edit", as: :edit_password 
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"



  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end
  

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You Must login first to do that" if Current.user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: 303
    end

    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
  end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash.now[:notice] = "Logged in successfully"
    # flash.now[:alert] = "Invalid credentials"
    
    # if session[:user_id]
    #   @user = User.find_by(id: session[:user_id])
    # end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      #send email
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "Check your mail to Reset Password"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "reset_password")

  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "your token has expired. Pls try again"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "reset_password")

    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Login with new password now"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
    #   flash[:alert] = "Something went worng"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In Successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/about/index.html.erb
<h1 class="text-muted d-flex justify-content-center">About Us</h1>

app/views/articles/_form.html.erb
<div class="container d-flex justify-content-center">
<%= form_with model: article do |form| %>
    <div>
      <%= form.label :title, class:"text-danger"%><br>
      <%= form.text_field :title %>
      <% if article.errors.full_messages_for(:title).any?%>
        <div class="alert alert-danger mt-2">
            <% article.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
      <%end%>
    </div>
  
    <div>
      <%= form.label :body, class:"text-danger"%><br>
      <%= form.text_area :body %><br>
      <%if article.errors.full_messages_for(:body).any?%>
        <div class="alert alert-danger mt-2">
            <% article.errors.full_messages_for(:body).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
      <%end%>
    </div>
  
    <div>
      <%= form.submit "Submit Post", class:"btn btn-primary mt-3"%>
    </div>
  <% end %>
</div>
  

app/views/articles/edit.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-secondary">Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article, class:"nav-link"%>
    </li>
  <% end %>
</ul>

<%= link_to "Create New Article", new_article_path, class:"nav-link"%>

app/views/articles/new.html.erb
<h1 class="text-secondary d-flex justify-content-center">New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1 class="text-primary"><%= @article.title %></h1>

<p class="text-secondary ps-3 fs-3"><%= @article.body %></p>

<ul>
  <li ><%= link_to "Edit", edit_article_path(@article), class:"nav-link " %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class:"nav-link text-danger"%></li>
</ul>


<h2 class="text-secondary mt-4 mb-4">Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter%>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }, class:"nav-link text-danger" %>
  </p>
<% end %>

<h2 class="text-secondary mt-5 mb-4">Add a comment:</h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter, class:"text-info mb-2" %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body, class:"text-info mb-2"%><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit "Post comment", class:"btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
  
    <div class="container">
      <%= render partial: "shared/flash"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-items-center text-danger">
  <h1>Welcome to tweets</h1>
</div>

app/views/password_resets/edit.html.erb
<h1 class="text-muted d-flex justify-content-center">Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form|%>


  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div><%= message%></div>
      <%end%>
    </div>
  <%end%>
  
  <div class="mb-3">
    <%= form.label :password, class:"mb-2"%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation, class:"mb-2"%>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder:"password"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class:"btn btn-primary"%>
  </div>
<%end %>

app/views/password_resets/new.html.erb
<h1 class="text-muted d-flex justify-content-center">Forgot Password ?</h1>

<%= form_with url: password_reset_path do |form|%>

  <div class="mb-3">
    <%= form.label :email, class:"mb-2"%>
    <%= form.text_field :email, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class:"btn btn-primary"%>
  </div>
<%end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice]%>
  </div>
<% end%>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert]%>
  </div>
<% end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to "Tweets", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link active"%>
       
        <%= link_to "About", about_url, class: "nav-link" %>

        
        <%= link_to "Read Blogs", read_articles_path, class:"nav-link"%>
      </div>

      <div class="navbar-nav ms-auto mb-2">
          <% if Current.user%>
              <span class="text-primary d-flex align-items-center border rounded fw-bold">
                <%= link_to Current.user.email, edit_password_path, class:"nav-link"%>
              </span>
              <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-secondary ms-2"%>
          <% else %>
            <%= link_to "Sign Up", sign_up_url, class: "nav-link" %>
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          <%end%>
      </div>
    </div>
  </div>
</nav>